#!/usr/bin/env python3
"""Merge build results (results.jsonl), the sweep (sw_render --sweep --json)
and the catalog into docs/COMPATIBILITY.md.

    tools/compat_report.py --results rootfs/results.jsonl --sweep sweep.json --out docs/COMPATIBILITY.md
"""
import argparse, json, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NEEDS = {"sf2": "a SoundFont (.sf2)", "minijv": "JV-880 ROMs", "rex": "REX loops", "mrsample": "samples",
         "breakbeat": "break samples", "granny": "samples", "mrdrums": "drum samples", "tablor": "wavetables (first run seeds them)",
         "radiogarden": "network", "webstream": "a stream URL + network", "airplay": "network (AirPlay)",
         "streamrtsp": "an RTSP stream", "dr32": "a drum kit (samples)", "chiptune": "a few hundred ms to boot its core"}
HEAVY = {"surge", "jp8000", "osirus", "helm", "sfz", "nam", "stems", "performance-fx", "stretch",
         "slicer", "freak", "plaits", "trance-gate", "davebox", "movy", "samplerobot"}

RECIPES = {k: v for k, v in json.load(open(os.path.join(ROOT, "tools", "recipes.json"))).items() if not k.startswith("_")}

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True); ap.add_argument("--sweep", required=True)
    ap.add_argument("--out", default=os.path.join(ROOT, "docs", "COMPATIBILITY.md"))
    a = ap.parse_args()
    cat = json.load(open(os.path.join(ROOT, "module-catalog.json")))["modules"]
    built = {}
    for l in open(a.results):
        r = json.loads(l)
        for m, s in r["modules"].items(): built[m] = (s, r["build"])
    sweep = {r["id"]: r for r in json.load(open(a.sweep))}
    issues = {"tablor": "upstream bug: crash if unloaded while loading (docs/UPSTREAM_ISSUES.md #1)",
              "scratch": "upstream bug: two instances loading at once abort (#2)"}
    rows = []
    for m in sorted(cat, key=lambda m: (m["component_type"], m["name"].lower())):
        i = m["id"]; s = sweep.get(i)
        if s and s.get("loaded"):
            status = "works" if s.get("rms", 0) >= 1e-4 else ("works, needs " + NEEDS[i] if i in NEEDS else "loads, silent in test")
            if not s.get("state"): status += "; state not restored"
        elif s:
            status = "fails: " + (s.get("crash") or s.get("error") or "not loaded")
        elif m["component_type"] in ("tool", "overtake") and (i in built and built[i][0] in ("ok", "no-binary", "no-binary (js-only?)", "not-built") and built[i][1] in ("ok",)):
            status = "Move-screen tool (JavaScript UI / overtake): no audio chain component to host"
        elif i in built and built[i][0] == "ok":
            status = "built; not a chain module (tool / overtake)"
        elif i in HEAVY:
            status = "not built on the Linux test box (large C++); build on macOS"
        else:
            b = built.get(i, ("not attempted", ""))
            rec = RECIPES.get(m["github_repo"], {})
            if rec.get("skip"): status = "nothing to build: " + rec["skip"]
            elif "cargo" in rec.get("requires", []): status = "needs Rust (cargo) to build"
            elif rec.get("requires"): status = "needs " + ", ".join(rec["requires"]) + " to build"
            else: status = "not built: " + (b[1] or b[0])
        if i in issues: status += " — " + issues[i]
        rows.append((m["component_type"], m["name"], i, m["github_repo"], status))
    with open(a.out, "w") as f:
        f.write("# Module compatibility\n\nGenerated by `tools/compat_report.py` from the build log and a "
                "`sw_render --sweep` run (48 kHz, 512-frame blocks; each module loaded in its own process, "
                "played, state saved and restored into a fresh instance).\n\n")
        n = sum(1 for r in rows if r[4].startswith("works"))
        f.write(f"**{n} of {len(rows)}** catalogue modules load, play and restore their state.\n\n")
        cur = None
        for t, name, i, repo, st in rows:
            if t != cur:
                f.write(f"\n## {t.replace('_', ' ')}\n\n| Module | id | Status |\n|---|---|---|\n"); cur = t
            f.write(f"| [{name}](https://github.com/{repo}) | `{i}` | {st} |\n")
    print(f"wrote {a.out}: {n}/{len(rows)} working")

if __name__ == "__main__":
    main()
